[package]
name = "nanstats"
version = "0.1.0"
edition = "2021"

[dependencies]
pulp = { version = "0.18", features = ["macro"] }

[features]
default = []
nightly = ["pulp/nightly"]

[dev-dependencies]
rand = "0.8"
divan = "0.1"
aligned-vec = "0.5"

[[bench]]
name = "benchmarks"
harness = false
